#!/usr/bin/env php
<?php

echo "CALLER: Setting MY_VAR=hello\n";
putenv('MY_VAR=hello');

echo "CALLER: Calling ./callee-php\n\n";
passthru('./callee-php');

echo "\nCALLER: Calling ./callee-bash\n\n";
passthru('./callee-bash');
